In [1]:
import pandas as pd

In [2]:
자전거 = pd.read_csv('타랑께_박수정.csv',index_col = 0)

In [3]:
자전거

,출발시각,열2,열1,도착시각,출발보관대,도착보관대,사용시간,출발지,도착지
자전거ID,,,,,,,,,
GJA-0141,20200701082504,20200701,82504,20200701083128,D-0021,D-0022,624,유안타증권 앞,상무역 5번 출구 앞
GJA-0073,20200701112145,20200701,112145,20200701122435,D-0020,D-0015,10290,교보문고 앞,한국은행 앞
GJA-0169,20200701113432,20200701,113432,20200701114431,D-0018,D-0020,999,아웃백스테이크 앞,교보문고 앞
GJA-0183,20200701114006,20200701,114006,20200701115905,D-0018,D-0020,1899,아웃백스테이크 앞,교보문고 앞
GJA-0166,20200701124544,20200701,124544,20200701125442,D-0018,D-0035,898,아웃백스테이크 앞,치평초교 앞
...,...,...,...,...,...,...,...,...,...
GJA-0115,20210205135943,20210205,135943,20210205140711,D-0035,D-0025,4768,치평초교 앞,계수초교 앞
GJA-0050,20210205141152,20210205,141152,20210205142957,D-0031,D-0035,1805,상무시민공원1,치평초교 앞
GJA-0089,20210205141641,20210205,141641,20210205153052,D-0022,D-0020,11411,상무역 5번 출구 앞,교보문고 앞
GJA-0035,20210205145055,20210205,145055,20210205184054,D-0000,D-0039,38999,광주시 111,김대중컨벤션센터1
GJA-0063,20210205151252,20210205,151252,20210205161137,D-0017,D-0000,9885,센트럴시티 앞,광주시 111

In [4]:
내자전거 = 자전거.loc[:, ['출발시각', '도착시각']]

In [5]:
내자전거

                    출발시각            도착시각
자전거ID
GJA-0141  20200701082504  20200701083128
GJA-0073  20200701112145  20200701122435
GJA-0169  20200701113432  20200701114431
GJA-0183  20200701114006  20200701115905
GJA-0166  20200701124544  20200701125442
...                  ...             ...
GJA-0115  20210205135943  20210205140711
GJA-0050  20210205141152  20210205142957
GJA-0089  20210205141641  20210205153052
GJA-0035  20210205145055  20210205184054
GJA-0063  20210205151252  20210205161137

[10865 rows x 2 columns]

In [6]:
내자전거.index

Index(['GJA-0141', 'GJA-0073', 'GJA-0169', 'GJA-0183', 'GJA-0166', 'GJA-0073',
       'GJA-0105', 'GJA-0121', 'GJA-0120', 'GJA-0045',
       ...
       'GJA-0157', 'GJA-0007', 'GJA-0153', 'GJA-0137', 'GJA-0098', 'GJA-0115',
       'GJA-0050', 'GJA-0089', 'GJA-0035', 'GJA-0063'],
      dtype='object', name='자전거ID', length=10865)

In [ ]:
type(내자전거)

In [7]:
내자전거.loc[:]['출발시각']

자전거ID
GJA-0141    20200701082504
GJA-0073    20200701112145
GJA-0169    20200701113432
GJA-0183    20200701114006
GJA-0166    20200701124544
                 ...
GJA-0115    20210205135943
GJA-0050    20210205141152
GJA-0089    20210205141641
GJA-0035    20210205145055
GJA-0063    20210205151252
Name: 출발시각, Length: 10865, dtype: int64

In [8]:
내자전거.columns

Index(['출발시각', '도착시각'], dtype='object')

In [9]:
자전거_출발 = 내자전거['출발시각']

In [10]:
자전거_출발

자전거ID
GJA-0141    20200701082504
GJA-0073    20200701112145
GJA-0169    20200701113432
GJA-0183    20200701114006
GJA-0166    20200701124544
                 ...
GJA-0115    20210205135943
GJA-0050    20210205141152
GJA-0089    20210205141641
GJA-0035    20210205145055
GJA-0063    20210205151252
Name: 출발시각, Length: 10865, dtype: int64

In [11]:
자전거_도착 = 내자전거['도착시각']

In [12]:
자전거_도착

자전거ID
GJA-0141    20200701083128
GJA-0073    20200701122435
GJA-0169    20200701114431
GJA-0183    20200701115905
GJA-0166    20200701125442
                 ...
GJA-0115    20210205140711
GJA-0050    20210205142957
GJA-0089    20210205153052
GJA-0035    20210205184054
GJA-0063    20210205161137
Name: 도착시각, Length: 10865, dtype: int64

In [139]:
자전거_도착 =자전거_도착.astype('str')

In [ ]:
from dateutil.parse import parse

In [ ]:
pip install parser

In [16]:
import datetime

In [13]:
자전거_출발[1]

20200701112145

In [ ]:
자전거_출발[0]

In [14]:
자전거_출발[len(자전거_출발)-1]

20210205151252

In [17]:
for i in 자전거_출발:
    date = i
    date_str = str(date)
    datetime.datetime.strptime(date_str,'%Y-%m-%d %H:%M:%S')

ValueError: time data '20200701082504' does not match format '%Y-%m-%d %H:%M:%S'

In [ ]:
자전거_출발

In [ ]:
자전거_출발 =자전거_출발.astype('str')

In [ ]:
자전거_출발

In [ ]:
import numpy as np
df = pd.concat([자전거_출발,자전거_도착])

In [ ]:
df

In [ ]:
자전거_출발 = 자전거_출발.tolist()

In [ ]:
자전거_출발

In [18]:
자전거_출발.info

AttributeError: 'Series' object has no attribute 'info'

In [19]:
from datetime import date,datetime,time

test_date = 자전거_출발[0]

In [20]:
test_date

20200701082504

In [21]:
c_date = datetime.datetime.strptime(test_date,"%Y%m%d%H%M%S")

AttributeError: type object 'datetime.datetime' has no attribute 'datetime'

In [ ]:
c_date

In [ ]:
a = c_date
a

In [22]:
df_list=[]
for i in 자전거_출발 :
    date = i
    c_date = datetime.strptime(date,"%Y%m%d%H%M%S")
    c_date=c_date.strftime('%Y-%m-%d %H:%M:%S')
    df_list.append(c_date)

TypeError: strptime() argument 1 must be str, not int

In [ ]:
df_list

In [136]:
자전거_도착 =자전거_도착.astype('str')

AttributeError: 'list' object has no attribute 'astype'

In [23]:
자전거_도착 = 자전거_도착.tolist()

In [24]:
자전거_도착

[20200701083128,
 20200701122435,
 20200701114431,
 20200701115905,
 20200701125442,
 20200701144258,
 20200701141849,
 20200701145333,
 20200701145445,
 20200701151417,
 20200701172620,
 20200701163733,
 20200701154126,
 20200701171141,
 20200701174805,
 20200701174629,
 20200701174647,
 20200701175131,
 20200701182319,
 20200701190735,
 20200701181932,
 20200701183904,
 20200701183913,
 20200701184028,
 20200701184401,
 20200701190124,
 20200701190028,
 20200701190050,
 20200701193644,
 20200701194905,
 20200701202438,
 20200701220704,
 20200702090944,
 20200702100131,
 20200702102211,
 20200702102210,
 20200702102414,
 20200702110631,
 20200702115149,
 20200702124327,
 20200702130201,
 20200702124845,
 20200702135105,
 20200702144253,
 20200702134417,
 20200702140354,
 20200702162113,
 20200702160252,
 20200702152922,
 20200702153125,
 20200702153125,
 20200702153137,
 20200702153127,
 20200702153828,
 20200702153821,
 20200702164828,
 20200702161231,
 20200702161222,
 20200702170114,
 20200702162619,
 20200702163336,
 20200702163336,
 20200702165325,
 20200702165343,
 20200702165624,
 20200702171546,
 20200702181207,
 20200702172505,
 20200702191140,
 20200702182104,
 20200702185614,
 20200702185142,
 20200702200758,
 20200702200754,
 20200702203410,
 20200703144227,
 20200703151543,
 20200703160144,
 20200703163016,
 20200703162759,
 20200703163930,
 20200703162837,
 20200703163016,
 20200703205601,
 20200703210619,
 20200704071624,
 20200704071534,
 20200704083635,
 20200704111627,
 20200704094119,
 20200704104731,
 20200704113546,
 20200704112748,
 20200704113600,
 20200704140725,
 20200704142039,
 20200704133215,
 20200704150021,
 20200704143629,
 20200704143645,
 20200704151554,
 20200704150226,
 20200704155127,
 20200704145648,
 20200704145635,
 20200704154509,
 20200704154509,
 20200704165506,
 20200704170703,
 20200704162548,
 20200704154917,
 20200704162554,
 20200704153638,
 20200704155515,
 20200704155510,
 20200704162428,
 20200704155757,
 20200704155706,
 20200704171301,
 20200704173354,
 20200704173347,
 20200704162807,
 20200704163042,
 20200704164638,
 20200704164640,
 20200704165857,
 20200704165855,
 20200704175634,
 20200704175618,
 20200704174305,
 20200704175447,
 20200704185944,
 20200704202811,
 20200704201412,
 20200704211806,
 20200704204436,
 20200704210359,
 20200705080436,
 20200705100424,
 20200705112307,
 20200705110313,
 20200705110542,
 20200705104933,
 20200705112410,
 20200705111533,
 20200705112929,
 20200705125541,
 20200705125509,
 20200705122846,
 20200705122853,
 20200705120538,
 20200705120549,
 20200705120334,
 20200705130510,
 20200705130510,
 20200705121404,
 20200705121442,
 20200705123708,
 20200705123659,
 20200705123616,
 20200705124530,
 20200705131759,
 20200705131413,
 20200705132640,
 20200705135511,
 20200705133949,
 20200705135452,
 20200705152358,
 20200705145607,
 20200705143951,
 20200705150738,
 20200705160808,
 20200705160826,
 20200705150741,
 20200705152554,
 20200705155727,
 20200705155750,
 20200705160659,
 20200705160246,
 20200705164024,
 20200705160839,
 20200705160842,
 20200705161645,
 20200705161524,
 20200705173308,
 20200705162325,
 20200705161743,
 20200705162313,
 20200705163236,
 20200705163229,
 20200705162300,
 20200705174938,
 20200705163052,
 20200705174926,
 20200705182338,
 20200705174429,
 20200705165935,
 20200705170853,
 20200705173015,
 20200705165459,
 20200705180949,
 20200705172742,
 20200705170348,
 20200705181712,
 20200705170535,
 20200705181642,
 20200705173250,
 20200705175153,
 20200705173500,
 20200705184652,
 20200705195140,
 20200705190148,
 20200705181422,
 20200705191256,
 20200705191304,
 20200705184806,
 20200705181808,
 20200705181806,
 20200705192734,
 20200705192752,
 20200705182540,
 20200705190747,
 20200705184402,
 20200705184403,
 20200705193803,
 20200705193745,
 20200705195213,
 20200705215345,
 20200705202834,
 20200705201147,
 20200705201130,
 20200705192821,
 20200705192741,
 20200705203431,
 20200705194236,
 20200705195612,
 20200705194803,
 20200705201409,
 20200705202238,
 20200705201729,
 20200705202618,
 20200705201049,
 20200705203102,
 20200705203201,
 20200705214528,
 20200705210334,
 20200705230508,
 20200706084235,
 20200706091654,
 20200706092102,
 20200706094313,
 20200706094546,
 20200706095012,
 20200706114556,
 20200706125356,
 20200706131323,
 20200706142155,
 20200706142151,
 20200706145525,
 20200706153109,
 20200706145533,
 20200706155016,
 20200706154812,
 20200706154134,
 20200706161235,
 20200706155612,
 20200706195244,
 20200706191400,
 20200706182106,
 20200706184827,
 20200706190433,
 20200706183128,
 20200706184832,
 20200706194411,
 20200706191037,
 20200706191040,
 20200706194344,
 20200706203536,
 20200706202900,
 20200706200815,
 20200706201516,
 20200706201231,
 20200706202909,
 20200706205907,
 20200706205636,
 20200706204751,
 20200706215721,
 20200706215730,
 20200706221137,
 20200707071835,
 20200707081401,
 20200707083412,
 20200707084359,
 20200707091344,
 20200707102938,
 20200707092959,
 20200707094130,
 20200707094505,
 20200707104833,
 20200707113836,
 20200707120011,
 20200707120157,
 20200707121633,
 20200707123848,
 20200707132239,
 20200707135734,
 20200707144634,
 20200707144752,
 20200707143344,
 20200707142749,
 20200707152326,
 20200707160815,
 20200707160826,
 20200707160809,
 20200707155836,
 20200707155736,
 20200707155802,
 20200707161023,
 20200707175255,
 20200707171838,
 20200707170539,
 20200707174247,
 20200707174148,
 20200707175852,
 20200707181359,
 20200707175512,
 20200707175746,
 20200707183805,
 20200707205310,
 20200707182424,
 20200707183329,
 20200707181947,
 20200707182736,
 20200707184114,
 20200707184111,
 20200707183722,
 20200707192212,
 20200707185152,
 20200708090443,
 20200707190455,
 20200707194535,
 20200707194527,
 20200707212648,
 20200707192157,
 20200707192230,
 20200707201943,
 20200707211749,
 20200707194110,
 20200707193853,
 20200708091343,
 20200708091952,
 20200707201011,
 20200707202240,
 20200707201335,
 20200707223048,
 20200707223736,
 20200707211159,
 20200707215608,
 20200707211138,
 20200707210641,
 20200707222700,
 20200708094234,
 20200708110634,
 20200708101653,
 20200708110630,
 20200708093013,
 20200708095127,
 20200708093544,
 20200708094422,
 20200708094528,
 20200708095501,
 20200708095351,
 20200708100919,
 20200708104929,
 20200708103924,
 20200708133637,
 20200708125428,
 20200708125443,
 20200708125700,
 20200708122500,
 20200708122550,
 20200708130054,
 20200708131947,
 20200708133357,
 20200708135653,
 20200708135203,
 20200708144106,
 20200708154521,
 20200708161735,
 20200708161925,
 20200708155116,
 20200708162639,
 20200708161219,
 20200708160732,
 20200708161955,
 20200708170733,
 20200708173502,
 20200708172316,
 20200708164752,
 20200708163950,
 20200708175547,
 20200708173248,
 20200708172856,
 20200708174633,
 20200708190243,
 20200708173114,
 20200708173114,
 20200708180901,
 20200708174247,
 20200708190252,
 20200708173734,
 20200708174403,
 20200708191942,
 20200708175537,
 20200708184915,
 20200708181108,
 20200708193428,
 20200708193440,
 20200708185026,
 20200708185009,
 20200708182608,
 20200708194134,
 20200708194126,
 20200708184403,
 20200708191524,
 20200708194000,
 20200708194654,
 20200708192134,
 20200708202556,
 20200708195353,
 20200708205132,
 20200708205122,
 20200708204013,
 20200708211232,
 20200708203134,
 20200708204745,
 20200708204812,
 20200708204058,
 20200708204057,
 20200708222442,
 20200708222520,
 20200708223120,
 20200708214009,
 20200708222428,
 20200708213631,
 20200708212747,
 20200803084932,
 20200803111015,
 20200803104452,
 20200803112947,
 20200803112953,
 20200803122512,
 20200803140745,
 20200803140745,
 20200803144200,
 20200803150504,
 20200803150544,
 20200803150728,
 20200803160242,
 20200803160117,
 20200803160141,
 20200803162348,
 20200803172423,
 20200803172504,
 20200803172452,
 20200803172013,
 20200803185946,
 20200803185907,
 20200804083818,
 20200803181706,
 20200803181233,
 20200803191812,
 20200803183657,
 20200803183935,
 20200803203413,
 20200803203412,
 20200803203418,
 20200803203401,
 20200803205354,
 20200804082535,
 20200804083717,
 20200804084929,
 20200804084937,
 20200804085350,
 20200804095649,
 20200804104010,
 20200804104113,
 20200804105409,
 20200804105336,
 20200804125508,
 20200804124207,
 20200804131314,
 20200804134501,
 20200804134442,
 20200804141831,
 20200804152255,
 20200804153014,
 20200804160225,
 20200804162131,
 20200804171045,
 20200804165425,
 20200804181639,
 20200804181836,
 20200804172426,
 20200804173348,
 20200804180124,
 20200804180752,
 20200804181840,
 20200804180910,
 20200804190219,
 20200804181659,
 20200804183123,
 20200804184043,
 20200804200052,
 20200804190040,
 20200804193459,
 20200804200510,
 20200804200606,
 20200804194124,
 20200804205043,
 20200804205139,
 20200804200122,
 20200804201916,
 20200804201732,
 20200804202158,
 20200804211837,
 20200804211728,
 20200805080639,
 20200805082000,
 20200805084047,
 20200805084439,
 20200805084416,
 20200805085945,
 20200805085703,
 20200805092253,
 20200805112655,
 20200805113916,
 20200805125222,
 20200805124307,
 20200805125556,
 20200805131217,
 20200805132057,
 20200805133130,
 20200805133344,
 20200805144304,
 20200805144342,
 20200805144705,
 20200805144158,
 20200805162834,
 20200805165207,
 20200805170440,
 20200805170936,
 20200805170119,
 20200805173107,
 20200805172501,
 20200805173218,
 20200805180142,
 20200805174055,
 20200805175621,
 20200805180120,
 20200805180219,
 20200805181908,
 20200805191506,
 20200805191552,
 20200805182016,
 20200805182037,
 20200805181829,
 20200805190714,
 20200805201013,
 20200805200126,
 20200805194759,
 20200805200738,
 20200805195129,
 20200805205832,
 20200805200548,
 20200805210020,
 20200805205905,
 20200805210006,
 20200805205054,
 20200806134427,
 20200806150437,
 20200806153208,
 20200806155816,
 20200806160820,
 20200806161846,
 20200806181243,
 20200806172510,
 20200806180506,
 20200806180351,
 20200806180452,
 20200806181222,
 20200806181909,
 20200807092542,
 20200806194644,
 20200806190507,
 20200806191309,
 20200806193416,
 20200806202741,
 20200806202647,
 20200806210856,
 20200806210112,
 20200807194544,
 20200808162601,
 20200808153319,
 20200808160309,
 20200808160302,
 20200808173359,
 20200808172044,
 20200808172141,
 20200809093057,
 20200808173439,
 20200808175906,
 20200808175804,
 20200808184235,
 20200808184325,
 20200808185606,
 20200808185720,
 20200808191925,
 20200808191926,
 20200808192742,
 20200808194600,
 20200808194621,
 20200808194626,
 20200808195427,
 20200808195314,
 20200808204936,
 20200808204831,
 20200808202039,
 20200808202043,
 20200808202142,
 20200808211410,
 20200808212631,
 20200808212716,
 20200809082909,
 20200809102214,
 20200809094903,
 20200809110419,
 20200809123510,
 20200809123511,
 20200809124653,
 20200809124549,
 20200809124700,
 20200809124430,
 20200809142028,
 20200809133523,
 20200809141329,
 20200809150204,
 20200809143115,
 20200809152157,
 20200809151241,
 20200809152215,
 20200809144130,
 20200809144056,
 20200809151148,
 20200809144126,
 20200809151148,
 20200809171703,
 20200809163236,
 20200809164107,
 20200809175533,
 20200809175539,
 20200809175546,
 20200809170754,
 20200809170813,
 20200809170912,
 20200809171027,
 20200809171045,
 20200809201337,
 20200809201352,
 20200809201341,
 20200809182259,
 20200809173003,
 20200809173106,
 20200809175337,
 20200809180505,
 20200809184549,
 20200809175711,
 20200809175248,
 20200809184159,
 20200809192422,
 20200809191905,
 20200809194433,
 20200809200125,
 20200809193146,
 20200809194437,
 20200809193013,
 20200809201919,
 20200809201908,
 20200809202037,
 20200809195154,
 20200809203023,
 20200809201038,
 20200809200955,
 20200809204408,
 20200809204025,
 20200809203239,
 20200809202332,
 20200809203150,
 20200809203225,
 20200809214401,
 20200809211256,
 20200809211343,
 20200809212518,
 20200809211519,
 20200809211532,
 20200809212641,
 20200809212528,
 20200809214056,
 20200809214216,
 20200810084409,
 20200810085223,
 20200810085119,
 20200810090525,
 20200810092338,
 20200810094837,
 20200810095120,
 20200810095207,
 20200810131511,
 20200810171444,
 20200810180431,
 20200810174220,
 20200810181410,
 20200810180500,
 20200810183750,
 20200810183750,
 20200810201231,
 20200810194644,
 20200810202122,
 20200810222438,
 20200811073941,
 20200811084548,
 20200811075542,
 20200811081902,
 20200811084318,
 20200811084421,
 20200811084932,
 20200811085601,
 20200811090157,
 20200811095715,
 20200811101543,
 20200811104606,
 20200811104602,
 20200811104506,
 20200811104700,
 20200811115854,
 20200811121856,
 20200811132650,
 20200811140531,
 20200811152749,
 20200811154714,
 20200811155625,
 20200811162954,
 20200811163805,
 20200811164637,
 20200811164156,
 20200811165037,
 20200811170829,
 20200811175804,
 20200811182324,
 20200811180949,
 20200811182127,
 20200811200023,
 20200811190032,
 20200811185915,
 20200811183511,
 20200811190010,
 20200811190053,
 20200811195423,
 20200811195511,
 20200811194144,
 20200811201853,
 20200811194911,
 20200811210400,
 20200811210403,
 20200811210504,
 20200811210622,
 20200811210522,
 20200811210503,
 20200811212331,
 20200812082016,
 20200812090053,
 20200812090212,
 20200812091607,
 20200812094615,
 20200812095131,
 20200812101613,
 20200812114306,
 20200812114409,
 20200812122552,
 20200812115752,
 20200812122157,
 20200812132021,
 20200812124051,
 20200812124148,
 20200812125345,
 20200812134826,
 20200812143139,
 20200812152303,
 20200812145045,
 20200812151746,
 20200812161114,
 20200812154231,
 20200812154411,
 20200812153708,
 20200812155945,
 20200812162146,
 20200812161523,
 20200812162619,
 20200812163351,
 20200812163706,
 20200812163717,
 20200812164649,
 20200812172728,
 20200812165219,
 20200812170945,
 20200812180054,
 20200812172330,
 20200812172139,
 20200812173231,
 20200812174047,
 20200812175636,
 20200812181810,
 20200812191726,
 20200812180926,
 20200812182105,
 20200812181717,
 20200812192509,
 20200812192335,
 20200812192351,
 20200812184643,
 20200812194538,
 20200812183913,
 20200812184629,
 20200812184759,
 20200812193645,
 20200812191610,
 20200812195518,
 20200812200521,
 20200812204902,
 20200812202505,
 20200812211822,
 20200812212057,
 20200812213930,
 20200812213940,
 20200812205512,
 20200812205620,
 20200812211725,
 20200812211743,
 20200813075603,
 20200813075118,
 20200813081206,
 20200813081510,
 20200813084319,
 20200813084449,
 20200813084750,
 20200813085604,
 20200813090850,
 20200813091725,
 20200813100347,
 20200813094659,
 20200813100350,
 20200813101505,
 20200813102609,
 20200813105530,
 20200813105016,
 20200813110530,
 20200813121511,
 20200813130727,
 20200813123647,
 20200813124132,
 20200813130028,
 20200813131717,
 20200813131152,
 20200813154734,
 20200813164242,
 20200813163917,
 20200813153415,
 20200813180928,
 20200813161421,
 20200813160519,
 20200813181242,
 20200813160532,
 20200813170642,
 20200813162836,
 20200813170652,
 20200813171956,
 20200813180752,
 20200813192401,
 20200813181157,
 20200813181657,
 20200813181308,
 20200813181626,
 20200813182152,
 20200813182459,
 20200813190209,
 20200813184058,
 20200813202727,
 20200813202735,
 20200813194156,
 20200813195636,
 20200813203908,
 20200813203902,
 20200813192016,
 20200813202402,
 20200813193518,
 20200813193508,
 20200813194857,
 20200813201525,
 20200813200629,
 20200813200632,
 20200813201508,
 20200813194846,
 20200813200222,
 20200813205719,
 20200813205916,
 20200813201816,
 20200813205022,
 20200813201604,
 20200813201702,
 20200813202535,
 20200813215140,
 20200813214836,
 20200813214841,
 20200813205818,
 20200813221325,
 20200813214858,
 20200813211340,
 20200813211324,
 20200814074041,
 20200814080821,
 20200814083520,
 20200814084502,
 20200814090703,
 20200814084940,
 20200814084929,
 20200814085155,
 20200814090105,
 20200814091054,
 20200814094522,
 20200814094936,
 20200814112836,
 20200814123234,
 20200814123234,
 20200814112542,
 20200814134742,
 20200814125037,
 20200814122751,
 20200814124116,
 20200814124343,
 20200814125744,
 20200814135503,
 20200814143011,
 20200814142203,
 20200814144943,
 20200814145746,
 20200814150123,
 20200814154320,
 20200814160937,
 20200814174059,
 20200814162010,
 20200814162612,
 20200814162312,
 20200814163908,
 20200814163627,
 20200814170605,
 20200814170532,
 20200814171943,
 20200814173115,
 20200814174116,
 20200814175707,
 20200814175840,
 20200814175833,
 20200814181422,
 20200814180849,
 20200814181848,
 20200814183049,
 20200814184559,
 20200814183035,
 20200814184331,
 20200814184104,
 20200814185621,
 20200814201549,
 20200814201515,
 20200814191249,
 20200814193200,
 20200814192827,
 20200814205839,
 20200814194841,
 20200814195822,
 20200814194259,
 20200814201056,
 20200814201855,
 20200814201856,
 20200814211212,
 20200814211217,
 20200814204015,
 20200814204155,
 20200814205903,
 20200814212713,
 20200814213305,
 ...]

In [25]:
df_list_3=[]
for a in 자전거_도착 :
    date_a = a
    c_date = datetime.strptime(date_a,"%Y%m%d%H%M%S")
    c_date=c_date.strftime('%Y-%m-%d %H:%M:%S')
    df_list_3.append(c_date)

TypeError: strptime() argument 1 must be str, not int

In [26]:
df_list_3

[]

In [27]:
자전거_시간 = pd.DateFrame([df_list,df_list3])

AttributeError: module 'pandas' has no attribute 'DateFrame'

In [28]:
df_출발 = pd.DataFrame(df_list)

In [29]:
df_출발

Empty DataFrame
Columns: []
Index: []

In [ ]:
자전거.loc[:,['자전거ID']]

In [ ]:
자전거.columns

In [ ]:
김자전거 = pd.read_csv('타랑께_김수정.csv')

In [ ]:
김자전거.columns

In [112]:
자전거id=김자전거.loc[:, ['자전거ID']]

In [ ]:
자전거id

In [147]:
df_도착 = pd.DataFrame(df_list_3)

In [ ]:
df_도착

In [ ]:
자전거_시간 = pd.DateFrame([df_list,df_list_2],columns=자전거id)

In [149]:
자전거_시간 = pd.concat([df_출발,df_도착],axis=1)

In [ ]:
자전거_시간

In [151]:
자전거_시간.columns = ['출발시각','도착시각']

In [152]:
자전거_시간.columns

Index(['출발시각', '도착시각'], dtype='object')

In [ ]:
자전거_시간

In [128]:
자전거_시간_임시=자전거_시간.T

In [ ]:
자전거_시간_임시 = 자전거_시간_임시.columns = 자전거id

In [157]:
자전거_시간

                      출발시각                 도착시각
0      2020-07-01 08:25:04  2020-07-01 08:31:28
1      2020-07-01 11:21:45  2020-07-01 12:24:35
2      2020-07-01 11:34:32  2020-07-01 11:44:31
3      2020-07-01 11:40:06  2020-07-01 11:59:05
4      2020-07-01 12:45:44  2020-07-01 12:54:42
...                    ...                  ...
10860  2021-02-05 13:59:43  2021-02-05 14:07:11
10861  2021-02-05 14:11:52  2021-02-05 14:29:57
10862  2021-02-05 14:16:41  2021-02-05 15:30:52
10863  2021-02-05 14:50:55  2021-02-05 18:40:54
10864  2021-02-05 15:12:52  2021-02-05 16:11:37

[10865 rows x 2 columns]

In [154]:
자전거_시간_임시 = 자전거_시간

In [ ]:
자전거_시간_임시.loc[:'소요시각'] = 자전거_시간_임시.loc[:'도착시각'] -자전거_시간_임시.loc[:'출발시각']

In [ ]:
for i in range(len(df_list)):
    df_list[i] = datetime.strptime(df_list[i] , '%Y%m%d%H%M%S')

In [159]:
자전거_시간.transpose()

,0,1,2,3,4,5,6,7,8,9,...,10855,10856,10857,10858,10859,10860,10861,10862,10863,10864
출발시각,2020-07-01 08:25:04,2020-07-01 11:21:45,2020-07-01 11:34:32,2020-07-01 11:40:06,2020-07-01 12:45:44,2020-07-01 13:42:32,2020-07-01 14:00:48,2020-07-01 14:10:01,2020-07-01 14:10:13,2020-07-01 14:12:44,...,2021-02-05 12:45:05,2021-02-05 12:49:30,2021-02-05 13:34:48,2021-02-05 13:46:07,2021-02-05 13:57:46,2021-02-05 13:59:43,2021-02-05 14:11:52,2021-02-05 14:16:41,2021-02-05 14:50:55,2021-02-05 15:12:52
도착시각,2020-07-01 08:31:28,2020-07-01 12:24:35,2020-07-01 11:44:31,2020-07-01 11:59:05,2020-07-01 12:54:42,2020-07-01 14:42:58,2020-07-01 14:18:49,2020-07-01 14:53:33,2020-07-01 14:54:45,2020-07-01 15:14:17,...,2021-02-05 12:53:16,2021-02-05 12:54:29,2021-02-05 13:59:27,2021-02-05 17:03:34,2021-02-05 14:09:07,2021-02-05 14:07:11,2021-02-05 14:29:57,2021-02-05 15:30:52,2021-02-05 18:40:54,2021-02-05 16:11:37

In [160]:
자전거_시간_결론= 자전거_시간.transpose()

In [ ]:
자전거_시간_결론.loc['소요시각'] = 자전거_시간_결론.loc['도착시각'] - 자전거_시간_결론.loc['출발시각']

In [165]:
자전거_시간_결론 = 자전거_시간_결론.transpose()

In [166]:
depart = 자전거_시간_결론['출발시각']

In [168]:
depart = depart.values.tolist()
for i in range(len(depart)):
    depart[i] = datetime.strptime(depart[i] , '%Y-%m-%d %H:%M:%S')

AttributeError: 'list' object has no attribute 'values'

In [170]:
자전거_시간_결론['출발시각'] = pd.to_datetime(자전거_시간_결론['출발시각'])

In [171]:
자전거_시간_결론['출발시각']

0       2020-07-01 08:25:04
1       2020-07-01 11:21:45
2       2020-07-01 11:34:32
3       2020-07-01 11:40:06
4       2020-07-01 12:45:44
                ...
10860   2021-02-05 13:59:43
10861   2021-02-05 14:11:52
10862   2021-02-05 14:16:41
10863   2021-02-05 14:50:55
10864   2021-02-05 15:12:52
Name: 출발시각, Length: 10865, dtype: datetime64[ns]

In [172]:
자전거_시간_결론['도착시각'] = pd.to_datetime(자전거_시간_결론['도착시각'])

In [173]:
자전거_시간_결론['도착시각']

0       2020-07-01 08:31:28
1       2020-07-01 12:24:35
2       2020-07-01 11:44:31
3       2020-07-01 11:59:05
4       2020-07-01 12:54:42
                ...
10860   2021-02-05 14:07:11
10861   2021-02-05 14:29:57
10862   2021-02-05 15:30:52
10863   2021-02-05 18:40:54
10864   2021-02-05 16:11:37
Name: 도착시각, Length: 10865, dtype: datetime64[ns]

In [174]:
자전거_시간_결론

                     출발시각                도착시각
0     2020-07-01 08:25:04 2020-07-01 08:31:28
1     2020-07-01 11:21:45 2020-07-01 12:24:35
2     2020-07-01 11:34:32 2020-07-01 11:44:31
3     2020-07-01 11:40:06 2020-07-01 11:59:05
4     2020-07-01 12:45:44 2020-07-01 12:54:42
...                   ...                 ...
10860 2021-02-05 13:59:43 2021-02-05 14:07:11
10861 2021-02-05 14:11:52 2021-02-05 14:29:57
10862 2021-02-05 14:16:41 2021-02-05 15:30:52
10863 2021-02-05 14:50:55 2021-02-05 18:40:54
10864 2021-02-05 15:12:52 2021-02-05 16:11:37

[10865 rows x 2 columns]

In [175]:
자전거_시간_결론 = 자전거_시간_결론.transpose()

In [176]:
자전거_시간_결론

,0,1,2,3,4,5,6,7,8,9,...,10855,10856,10857,10858,10859,10860,10861,10862,10863,10864
출발시각,2020-07-01 08:25:04,2020-07-01 11:21:45,2020-07-01 11:34:32,2020-07-01 11:40:06,2020-07-01 12:45:44,2020-07-01 13:42:32,2020-07-01 14:00:48,2020-07-01 14:10:01,2020-07-01 14:10:13,2020-07-01 14:12:44,...,2021-02-05 12:45:05,2021-02-05 12:49:30,2021-02-05 13:34:48,2021-02-05 13:46:07,2021-02-05 13:57:46,2021-02-05 13:59:43,2021-02-05 14:11:52,2021-02-05 14:16:41,2021-02-05 14:50:55,2021-02-05 15:12:52
도착시각,2020-07-01 08:31:28,2020-07-01 12:24:35,2020-07-01 11:44:31,2020-07-01 11:59:05,2020-07-01 12:54:42,2020-07-01 14:42:58,2020-07-01 14:18:49,2020-07-01 14:53:33,2020-07-01 14:54:45,2020-07-01 15:14:17,...,2021-02-05 12:53:16,2021-02-05 12:54:29,2021-02-05 13:59:27,2021-02-05 17:03:34,2021-02-05 14:09:07,2021-02-05 14:07:11,2021-02-05 14:29:57,2021-02-05 15:30:52,2021-02-05 18:40:54,2021-02-05 16:11:37

In [178]:
자전거_시간_결론.loc['사용시간'] = 자전거_시간_결론.loc['도착시각']- 자전거_시간_결론.loc['출발시각']

In [179]:
자전거_시간_결론

,0,1,2,3,4,5,6,7,8,9,...,10855,10856,10857,10858,10859,10860,10861,10862,10863,10864
출발시각,2020-07-01 08:25:04,2020-07-01 11:21:45,2020-07-01 11:34:32,2020-07-01 11:40:06,2020-07-01 12:45:44,2020-07-01 13:42:32,2020-07-01 14:00:48,2020-07-01 14:10:01,2020-07-01 14:10:13,2020-07-01 14:12:44,...,2021-02-05 12:45:05,2021-02-05 12:49:30,2021-02-05 13:34:48,2021-02-05 13:46:07,2021-02-05 13:57:46,2021-02-05 13:59:43,2021-02-05 14:11:52,2021-02-05 14:16:41,2021-02-05 14:50:55,2021-02-05 15:12:52
도착시각,2020-07-01 08:31:28,2020-07-01 12:24:35,2020-07-01 11:44:31,2020-07-01 11:59:05,2020-07-01 12:54:42,2020-07-01 14:42:58,2020-07-01 14:18:49,2020-07-01 14:53:33,2020-07-01 14:54:45,2020-07-01 15:14:17,...,2021-02-05 12:53:16,2021-02-05 12:54:29,2021-02-05 13:59:27,2021-02-05 17:03:34,2021-02-05 14:09:07,2021-02-05 14:07:11,2021-02-05 14:29:57,2021-02-05 15:30:52,2021-02-05 18:40:54,2021-02-05 16:11:37
사용시간,0 days 00:06:24,0 days 01:02:50,0 days 00:09:59,0 days 00:18:59,0 days 00:08:58,0 days 01:00:26,0 days 00:18:01,0 days 00:43:32,0 days 00:44:32,0 days 01:01:33,...,0 days 00:08:11,0 days 00:04:59,0 days 00:24:39,0 days 03:17:27,0 days 00:11:21,0 days 00:07:28,0 days 00:18:05,0 days 01:14:11,0 days 03:49:59,0 days 00:58:45

In [181]:
자전거_시간_결론 = 자전거_시간_결론.transpose()

In [182]:
자전거_시간_결론

                     출발시각                도착시각            사용시간
0     2020-07-01 08:25:04 2020-07-01 08:31:28 0 days 00:06:24
1     2020-07-01 11:21:45 2020-07-01 12:24:35 0 days 01:02:50
2     2020-07-01 11:34:32 2020-07-01 11:44:31 0 days 00:09:59
3     2020-07-01 11:40:06 2020-07-01 11:59:05 0 days 00:18:59
4     2020-07-01 12:45:44 2020-07-01 12:54:42 0 days 00:08:58
...                   ...                 ...             ...
10860 2021-02-05 13:59:43 2021-02-05 14:07:11 0 days 00:07:28
10861 2021-02-05 14:11:52 2021-02-05 14:29:57 0 days 00:18:05
10862 2021-02-05 14:16:41 2021-02-05 15:30:52 0 days 01:14:11
10863 2021-02-05 14:50:55 2021-02-05 18:40:54 0 days 03:49:59
10864 2021-02-05 15:12:52 2021-02-05 16:11:37 0 days 00:58:45

[10865 rows x 3 columns]

In [183]:
자전거_시간_결론.to_csv('자전거_사용시간.csv',index=True,encoding='cp949')